In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Working With Git

In [2]:
%cd /content/drive/My\ Drive/

/content/drive/My Drive

In [3]:
!git clone https://github.com/SwathiJakka/ASCEND_Capstone

fatal: destination path 'ASCEND_Capstone' already exists and is not an empty directory.

# Imoprt Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Read the Mereged Data "dataSignUp.csv"

- from git repo read the dataset

In [3]:
df = pd.read_csv("/content/drive/MyDrive/ASCEND_Capstone/datasets/data_signup.csv")
df.shape

(915, 38)

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
print(df['Program Version'].unique())

['Online' 'Blended' 'French Facilitator' 'Individual' nan 'French' 'SDECB']

# Spliting the dataset

### _*split the dataframe as*_
- 1. English User:  if the "Program Version" = 'Online' ,'Blended', 'Individual','SDECB','nan'
- 2. French User : if the "Program Version" =  'French Facilitator' or 'French'

In [6]:
# Define the criteria for splitting
english_programs = ['Online', 'Blended', 'Individual', None]
french_programs = ['French','SDECB']

# Filter the DataFrame for English Users
english_users = df[df['Program Version'].isin(english_programs)]

# Filter the DataFrame for French Users
french_users = df[df['Program Version'].isin(french_programs)]

In [7]:
# Display the results
print("English Users:")
english_users.head()

English Users:

,Username,FirstName,LastName,EmailAddress,Phone,City,Province,Country,Gender,Age,Status in Canada,Marital Status,Country of birth,Country you have_will immigrate from,Year landed in Canada enter 0 if not yet landed,Highest level of education,Cohort Name,Program Version,What is your current employment status,What industry or sector are you working in,Is this your preferred industry or sector,What is your current annual employment salary,Genre,Âge,Statut au Canada,Situation maritale,Pays de naissance,Pays doù vous avez immigré immigrerez,Année darrivée au Canada saisir 0 si non applicable,Principale langue parlée à la maison,Plus haut niveau de formation,Quelle est votre situation professionnelle actuelle,Dans quelle industrie ou secteur travaillez vous,Est ce votre industrie ou secteur de prédilection,Quel est votre salaire annuel actuel,Organization,DateAdded,Quarterly
0,10049na@gmail.com,Gyeonghui,Seong,10049na@gmail.com,2368381714,Victoria,British Columbia,Canada,Female,50-59,Permanent Resident (In Canada),Separated/divorced,Korea,Korea,2021.0,Degree,"VIRCS Feb - Apr, 2024",Online,5) Unemployed,01) I am not currently employed,2) No,1) I am not currently employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-02-05 17:31,Jan 2024 - Mar 2024
1,abdoalnaser085@hotmail.com,Abdoalnaser,Ibrahim,abdoalnaser085@hotmail.com,6475816128,Niagara Falls,Ontario,Canada,Male,20-29,Convention Refugee,Single,Sudan,Sudan,2022.0,Graduate degree,"NFAMC Jan - Mar, 2024",Online,5) Unemployed,"03) Mining, quarrying, and oil and gas extraction",1) Yes,1) I am not currently employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-02-05 15:29,Jan 2024 - Mar 2024
2,abeywarnalakshi@gmail.com,LAKSHI MADUSHA,ABEYWARNA,abeywarnalakshi@gmail.com,+1 506 897 4328,Fredericton,New Brunswick,Canada,Female,30-39,Permanent Resident (In Canada),Married/live with partner,Sri Lanka,Sri Lanka,2022.0,Diploma,"MCAF Feb - Apr, 2024",Online,1) Employed,17) Health care and social assistance,1) Yes,"3) $25,000  $50,000",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-02-26 21:02,Jan 2024 - Mar 2024
3,ac25@ukr.net,Anastasiia,Sheremetieva,ac25@ukr.net,7783893914,North Vancouver,British Columbia,Canada,Female,30-39,Temporary Foreign Worker (IRPR s.112 work permit),Married/live with partner,Ukraine,Ukraine,2022.0,Degree,"VCC Mar - May, 2024",Online,1) Employed,17) Health care and social assistance,1) Yes,"3) $25,000  $50,000",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-03-23 5:19,Jan 2024 - Mar 2024
4,adebola.makinde@yahoo.com,Yetunde Adebola,Makinde,adebola.makinde@yahoo.com,6139708186,Brantford,Ontario,Canada,Female,30-39,Permanent Resident (In Canada),Married/live with partner,Nigeria,Nigeria,0.0,Graduate degree,"PIACS Mar-May, 2024",Online,2) In school or training,01) I am not currently employed,2) No,1) I am not currently employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-03-29 1:04,Jan 2024 - Mar 2024

In [8]:
print("\nFrench Users:")
french_users.head()

French Users:

,Username,FirstName,LastName,EmailAddress,Phone,City,Province,Country,Gender,Age,Status in Canada,Marital Status,Country of birth,Country you have_will immigrate from,Year landed in Canada enter 0 if not yet landed,Highest level of education,Cohort Name,Program Version,What is your current employment status,What industry or sector are you working in,Is this your preferred industry or sector,What is your current annual employment salary,Genre,Âge,Statut au Canada,Situation maritale,Pays de naissance,Pays doù vous avez immigré immigrerez,Année darrivée au Canada saisir 0 si non applicable,Principale langue parlée à la maison,Plus haut niveau de formation,Quelle est votre situation professionnelle actuelle,Dans quelle industrie ou secteur travaillez vous,Est ce votre industrie ou secteur de prédilection,Quel est votre salaire annuel actuel,Organization,DateAdded,Quarterly
21,asouid@cdene.ns.ca,AMEL,SOUID,asouid@cdene.ns.ca,9024247052,Halifax,Nova Scotia,Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CDENE Mar - May, 2024",French,NaN,NaN,NaN,NaN,Femme,40-49,Résident.e permanent.e (au Canada),Marié.e / En concubinage,Algérie,Algérie,2022,NaN,Maîtrise,Employé.e,21) Autres services,Oui,"Plus de $100,000",CDENE,2024-03-21 19:13,Jan 2024 - Mar 2024
22,badreddine.marouane@gmail.com,Badreddine,Marouane,badreddine.marouane@gmail.com,4376656257,TORONTO,Ontario,Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"AFRY Mar - May, 2024",French,NaN,NaN,NaN,NaN,Homme,30-39,Résident.e permanent.e (au Canada),Marié.e / En concubinage,Maroc,Maroc,2023,NaN,Baccalauréat,Employé.e,21) Autres services,Non,"$25,000  $50,000",AFRY,2024-03-25 20:13,Jan 2024 - Mar 2024
28,bigdave75002@gmail.com,David Olivier Donat,Kitenge,bigdave75002@gmail.com,4373652012,Toronto,Ontario,Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"AFRY Mar - May, 2024",French,NaN,NaN,NaN,NaN,Homme,20-29,Réfugié.e au sens de la Convention,Célibataire,Republique Democratique du Congo,USA,2023,NaN,Formation post-secondaire non-diplômante (écol...,Sans emploi,21) Autres services,Oui,Je suis actuellement sans emploi,AFRY,2024-03-27 17:59,Jan 2024 - Mar 2024
29,carol_liseth@hotmail.com,Carolina,Castillo,carol_liseth@hotmail.com,2369715690,Burnaby,British Columbia,Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SDECB Jan-Mar 2024,French,NaN,NaN,NaN,NaN,Femme,30-39,Résident.e permanent.e (au Canada),NaN,Equateur,Equateur,2023,NaN,Maîtrise,Sans emploi,20) Administration publique,Oui,Je suis actuellement sans emploi,Le Relais Francophone,2024-01-23 1:22,Jan 2024 - Mar 2024
58,Faiza.abdesselam2@gmail.com,FAIZA,ABDESSELAM,Faiza.abdesselam2@gmail.com,6474021354,Ottawa,Ontario,Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"AFRY Mar - May, 2024",French,NaN,NaN,NaN,NaN,Femme,40-49,Résident.e permanent.e (au Canada),Célibataire,Algérie,Algérie,15 novembre 2022,NaN,Maîtrise,Sans emploi,01) Je suis actuellement sans emploi,Non,Je suis actuellement sans emploi,AFRY,2024-03-30 12:09,Jan 2024 - Mar 2024

# DATA CLEANING FOR ENGLISH USER

In [9]:
english_users.shape

(850, 38)

In [10]:
english_users.columns

Index(['Username', 'FirstName', 'LastName', 'EmailAddress', 'Phone', 'City',
       'Province', 'Country', 'Gender', 'Age', 'Status in Canada',
       'Marital Status', 'Country of birth',
       'Country you have_will immigrate from',
       'Year landed in Canada enter 0 if not yet landed',
       'Highest level of education', 'Cohort Name', 'Program Version',
       'What is your current employment status',
       'What industry or sector are you working in',
       'Is this your preferred industry or sector',
       'What is your current annual employment salary', 'Genre', 'Âge',
       'Statut au Canada', 'Situation maritale', 'Pays de naissance',
       'Pays doù vous avez immigré immigrerez',
       'Année darrivée au Canada saisir 0 si non applicable',
       'Principale langue parlée à la maison', 'Plus haut niveau de formation',
       'Quelle est votre situation professionnelle actuelle ',
       'Dans quelle industrie ou secteur travaillez vous',
       'Est ce votre industrie ou secteur de prédilection',
       'Quel est votre salaire annuel actuel', 'Organization', 'DateAdded',
       'Quarterly'],
      dtype='object')

# Removing the Columns from EnglishUser Dataset

In [11]:
# List of columns to drop
Engcolumns_to_drop = ['Genre', 'Âge', 'Statut au Canada', 'Situation maritale', 'Pays de naissance', 'Pays doù vous avez immigré immigrerez', 'Année darrivée au Canada saisir 0 si non applicable', 'Principale langue parlée à la maison', 'Plus haut niveau de formation', 'Quelle est votre situation professionnelle actuelle ', 'Dans quelle industrie ou secteur travaillez vous', 'Est ce votre industrie ou secteur de prédilection', 'Quel est votre salaire annuel actuel',]

# Create a new dataframe by dropping the specified columns
english_users = english_users.drop(Engcolumns_to_drop, axis=1)

In [12]:
english_users.shape

(850, 25)

In [13]:
english_users.columns

Index(['Username', 'FirstName', 'LastName', 'EmailAddress', 'Phone', 'City',
       'Province', 'Country', 'Gender', 'Age', 'Status in Canada',
       'Marital Status', 'Country of birth',
       'Country you have_will immigrate from',
       'Year landed in Canada enter 0 if not yet landed',
       'Highest level of education', 'Cohort Name', 'Program Version',
       'What is your current employment status',
       'What industry or sector are you working in',
       'Is this your preferred industry or sector',
       'What is your current annual employment salary', 'Organization',
       'DateAdded', 'Quarterly'],
      dtype='object')

In [14]:
print(english_users['Program Version'].unique())

['Online' 'Blended' 'Individual']

In [15]:
english_users.isnull().sum()

Username                                             0
FirstName                                            0
LastName                                             0
EmailAddress                                         0
Phone                                                0
City                                                 0
Province                                             0
Country                                              0
Gender                                               0
Age                                                  0
Status in Canada                                     0
Marital Status                                       0
Country of birth                                     0
Country you have_will immigrate from                 4
Year landed in Canada enter 0 if not yet landed      0
Highest level of education                           0
Cohort Name                                          0
Program Version                                      0
What is your current employment status               1
What industry or sector are you working in           1
Is this your preferred industry or sector            1
What is your current annual employment salary        1
Organization                                       814
DateAdded                                            0
Quarterly                                            0
dtype: int64

In [16]:

# Define the path where you want to save the CSV file
save_path = os.path.join(os.getcwd(), 'english_users.csv')

# Save the english_users DataFrame to a CSV file
english_users.to_csv(save_path, index=False)

# Function to return the save path
def get_save_path():
    return save_path

# Print the path where the dataset has been saved
print(f"English users dataset has been saved at: {get_save_path()}")

NameError: name 'os' is not defined

# Data Cleaning

## __1st block__

remove from records if "FirstName" is in
- 'The ASCEND', 'Test', 'Test1', 'Testing'


## __2nd block__

Remove / drop / delete all the records if the "Username" is in

- ends with ''@ascend.com'
- starts with 'test', 'proton', 'demo'

In [17]:
# Define the list of first names to be removed
names_to_remove = ['The ASCEND', 'Test', 'Test1', 'Testing']

# Remove records with the specified first names
english_users_cleaned = english_users[~english_users['FirstName'].isin(names_to_remove)]
english_users_cleaned.shape

(839, 25)

In [18]:
# Find the indices of rows that meet the conditions
indices_to_drop = english_users_cleaned[(english_users_cleaned['Username'].str.endswith('@ascend.com')) |
                               (english_users_cleaned['Username'].str.startswith(('test', 'proton', 'demo')))].index

# Drop the rows based on the indices
english_users_cleaned.drop(indices_to_drop, inplace=True)

# Display the modified DataFrame
print("\nDataFrame after removing records:")
english_users_cleaned.shape

DataFrame after removing records:

<ipython-input-18-9c613937508c>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  english_users_cleaned.drop(indices_to_drop, inplace=True)

(839, 25)

In [19]:
english_users_cleaned_copy = english_users_cleaned.copy()

In [ ]:
# # Define a function to check if a value looks like a date
# def looks_like_date(value):
#     import re
#     date_patterns = [
#         r'\d{1,2}-[A-Za-z]{3}',  # e.g., 12-Sep
#         r'[A-Za-z]{3} \d{1,2} \d{4}',  # e.g., OCT 11 1973
#         r'[A-Za-z]{4,9}-\d{2}-\d{4}',  # e.g., june-03-1991
#         r'\d{2}/\d{2}/\d{4}',  # e.g., 24/12/1994
#         r'\d{1,2}/\d{1,2}/\d{4}',  # e.g., 1/1/1993
#         r'\d{4}/[A-Za-z]{4,9} \d{1,2}'  # e.g., 1967/september 24
#     ]
#     return any(re.match(pattern, str(value)) for pattern in date_patterns)

# # Apply the function to identify date-like entries
# is_date = english_users_cleaned_copy['Country of birth'].apply(looks_like_date)

# # Replace date-like entries with the corresponding values from "Country you have_will immigrate from"
# english_users_cleaned_copy.loc[is_date, 'Country of birth'] = english_users_cleaned_copy.loc[is_date, 'Country you have_will immigrate from']

# # Display the modified DataFrame
# print("\nDataFrame after cleaning:")
# print(english_users_cleaned_copy)

In [34]:
# # Define a function to check if a value looks like a date
# def looks_like_date(value):
#     import re
#     date_patterns = [
#         r'\d{1,2}-[A-Za-z]{3}',  # e.g., 12-Sep
#         r'[A-Za-z]{3} \d{1,2} \d{4}',  # e.g., OCT 11 1973
#         r'[A-Za-z]{4,9}-\d{2}-\d{4}',  # e.g., june-03-1991
#         r'\d{2}/\d{2}/\d{4}',  # e.g., 24/12/1994
#         r'\d{1,2}/\d{1,2}/\d{4}',  # e.g., 1/1/1993
#         r'\d{4}/[A-Za-z]{4,9} \d{1,2}'  # e.g., 1967/september 24
#     ]
#     return any(re.match(pattern, str(value)) for pattern in date_patterns)

# # Make a copy of the original 'Country of birth' column for comparison later
# original_country_of_birth = english_users_cleaned_copy1['Country of birth'].copy()

# # Apply the function to identify date-like entries
# is_date = english_users_cleaned_copy1['Country of birth'].apply(looks_like_date)

# # Replace date-like entries with the corresponding values from "Country you have_will immigrate from"
# english_users_cleaned_copy1.loc[is_date, 'Country of birth'] = english_users_cleaned_copy1.loc[is_date, 'Country you have_will immigrate from']

In [ ]:
# # Display the modified DataFrame
# print("\nDataFrame after cleaning:")
# print(english_users_cleaned_copy1)

# # Show only the rows where 'Country of birth' has changed
# changed_rows = english_users_cleaned_copy1[original_country_of_birth != english_users_cleaned['Country of birth']]

# print("\nRows where 'Country of birth' has changed:")
# print(changed_rows)

In [20]:
english_users_cleaned_copy.isnull().sum()

Username                                             0
FirstName                                            0
LastName                                             0
EmailAddress                                         0
Phone                                                0
City                                                 0
Province                                             0
Country                                              0
Gender                                               0
Age                                                  0
Status in Canada                                     0
Marital Status                                       0
Country of birth                                     0
Country you have_will immigrate from                 4
Year landed in Canada enter 0 if not yet landed      0
Highest level of education                           0
Cohort Name                                          0
Program Version                                      0
What is your current employment status               1
What industry or sector are you working in           1
Is this your preferred industry or sector            1
What is your current annual employment salary        1
Organization                                       803
DateAdded                                            0
Quarterly                                            0
dtype: int64

# Handling special cases

- for 'Country of birth'
- for 'Country you will migrate from'

In [21]:
import pandas as pd

# Assuming you have already loaded the pandas library and your DataFrame is named 'english_users_cleaned'

# Define a function to check if a value looks like a date
def looks_like_date(value):
    import re
    date_patterns = [
        r'\d{1,2}-[A-Za-z]{3}',  # e.g., 12-Sep
        r'[A-Za-z]{3} \d{1,2} \d{4}',  # e.g., OCT 11 1973
        r'[A-Za-z]{4,9}-\d{2}-\d{4}',  # e.g., june-03-1991
        r'\d{2}/\d{2}/\d{4}',  # e.g., 24/12/1994
        r'\d{1,2}/\d{1,2}/\d{4}',  # e.g., 1/1/1993
        r'\d{4}/[A-Za-z]{4,9} \d{1,2}',  # e.g., 1967/september 24
        r'\d{1,2}/\d{1,2}/\d{4}',  # e.g., 9/9/1990
        r'[A-Za-z]{3,9}-\d{1,2}-\d{4}'  # e.g., june-03-1991
    ]
    return any(re.match(pattern, str(value)) for pattern in date_patterns)

# Make a copy of the original 'Country of birth' column for comparison later
original_country_of_birth = english_users_cleaned_copy['Country of birth'].copy()

# Apply the function to identify date-like entries
is_date = english_users_cleaned_copy['Country of birth'].apply(looks_like_date)

# Replace date-like entries with the corresponding values from "Country you have_will immigrate from"
english_users_cleaned_copy.loc[is_date, 'Country of birth'] = english_users_cleaned_copy.loc[is_date, 'Country you have_will immigrate from']

# Show only the rows where 'Country of birth' has changed
changed_rows = english_users_cleaned_copy[original_country_of_birth != english_users_cleaned_copy['Country of birth']]

print("\nRows where 'Country of birth' has changed:")
changed_rows

Rows where 'Country of birth' has changed:

,Username,FirstName,LastName,EmailAddress,Phone,City,Province,Country,Gender,Age,Status in Canada,Marital Status,Country of birth,Country you have_will immigrate from,Year landed in Canada enter 0 if not yet landed,Highest level of education,Cohort Name,Program Version,What is your current employment status,What industry or sector are you working in,Is this your preferred industry or sector,What is your current annual employment salary,Organization,DateAdded,Quarterly
16,anxu825@gmail.com,Guifen,Xu,anxu825@gmail.com,3064506011,Beijing,Beijing,China,Female,30-39,Permanent Resident (In Canada),Married/live with partner,China,China,2021.0,Degree,"RIWC Jan - Mar, 2024",Blended,5) Unemployed,01) I am not currently employed,2) No,1) I am not currently employed,NaN,2024-01-10 6:53,Jan 2024 - Mar 2024
92,jiangbaoping@gmail.com,BOBBIE,JIANG,jiangbaoping@gmail.com,7789527298,Vancouver,British Columbia,Canada,Female,50-59,Permanent Resident (In Canada),Prefer not to disclose,China,China,2012.0,Degree,"VCC Mar - May, 2024",Online,5) Unemployed,01) I am not currently employed,1) Yes,1) I am not currently employed,NaN,2024-03-22 22:56,Jan 2024 - Mar 2024
95,jinuankur20@gmail.com,Jinali,Patel,jinuankur20@gmail.com,7805476331,Lasalle,Ontario,Canada,Female,30-39,Permanent Resident (In Canada),Married/live with partner,india,india,2021.0,Graduate degree,"WEST EWE Feb - Apr, 2024",Blended,5) Unemployed,06) Manufacturing,1) Yes,"2) Less than $25,000",NaN,2024-02-05 17:49,Jan 2024 - Mar 2024
125,manasaguruprasad24@gmail.com,Manasa,Guruprasad,manasaguruprasad24@gmail.com,6728551553,Surrey,British Columbia,Canada,Female,20-29,Permanent Resident (In Canada),Married/live with partner,India,India,2023.0,Some post-secondary (college or university cou...,"ISS of BC (Feb - Apr, 2024)",Online,5) Unemployed,01) I am not currently employed,2) No,1) I am not currently employed,NaN,2024-02-12 18:17,Jan 2024 - Mar 2024
183,raulcan333@gmail.com,German,Alvarez,raulcan333@gmail.com,4373312775,Winnipeq,Manitoba,Canada,Male,50-59,Convention Refugee,Married/live with partner,Colombia,Colombia,2023.0,Graduate degree,"EO (Jan - Mar, 2024)",Online,5) Unemployed,01) I am not currently employed,2) No,1) I am not currently employed,NaN,2024-01-29 22:13,Jan 2024 - Mar 2024
200,shrfaldynshyma@gmail.com,Shaima,Sharaf Aldeen,shrfaldynshyma@gmail.com,4373328474,Mississauga,Hajjah,Yemen,Female,20-29,Permanent Resident (In Canada),Married/live with partner,Lebanon,Lebanon,2023.0,Degree,"PIACS Mar-May, 2024",Online,5) Unemployed,01) I am not currently employed,2) No,1) I am not currently employed,NaN,2024-03-28 21:45,Jan 2024 - Mar 2024
315,chililian002@yahoo.com,Lilian,Iwu,chililian002@yahoo.com,16399994686,Regina,Saskatchewan,Canada,Female,40-49,Permanent Resident (In Canada),Single,Nigeria,Nigeria,2023.0,Graduate degree,"RIWC Jul - Oct, 2023",Blended,5) Unemployed,17) Health care and social assistance,1) Yes,"3) $25,000  $50,000",NaN,2023-07-24 11:15,July 2023 - Sep 2023
360,fessehad27@gmail.com,FESSEHA,TEWOLDEMDHIN,fessehad27@gmail.com,7785876427,Victoria,British Columbia,Canada,Male,40-49,Permanent Resident (In Canada),Married/live with partner,Yes,Yes,0.0,Diploma,"VIRCS Jul - Sep, 2023",Online,1) Employed,05) Construction,1) Yes,"2) Less than $25,000",NaN,2023-07-25 19:32,July 2023 - Sep 2023
392,hong008sec@hotmail.com,Liping,Wang,hong008sec@hotmail.com,2508120372,victoria,British Columbia,Canada,Female,50-59,Permanent Resident (In Canada),Single,slaes manager,slaes manager,2020.0,Less than high school,"VIRCS Jul - Sep, 2023",Online,5) Unemployed,01) I am not currently employed,1) Yes,1) I am not currently employed,NaN,2023-07-25 10:57,July 2023 - Sep 2023

In [22]:
import pandas as pd

# Assuming 'english_users_cleaned_copy' is already loaded in your environment

# Define the condition for the specific 'Username'
condition = english_users_cleaned_copy['Username'] == 'fessehad27@gmail.com'

# Update the 'Country of birth' and 'Country you have_will immigrate from' columns
english_users_cleaned_copy.loc[condition, ['Country of birth', 'Country you have_will immigrate from']] = 'Euthiopia'

# Print only the specific record to verify the changes
english_users_cleaned_copy.loc[condition]

,Username,FirstName,LastName,EmailAddress,Phone,City,Province,Country,Gender,Age,Status in Canada,Marital Status,Country of birth,Country you have_will immigrate from,Year landed in Canada enter 0 if not yet landed,Highest level of education,Cohort Name,Program Version,What is your current employment status,What industry or sector are you working in,Is this your preferred industry or sector,What is your current annual employment salary,Organization,DateAdded,Quarterly
360,fessehad27@gmail.com,FESSEHA,TEWOLDEMDHIN,fessehad27@gmail.com,7785876427,Victoria,British Columbia,Canada,Male,40-49,Permanent Resident (In Canada),Married/live with partner,Euthiopia,Euthiopia,0.0,Diploma,"VIRCS Jul - Sep, 2023",Online,1) Employed,05) Construction,1) Yes,"2) Less than $25,000",NaN,2023-07-25 19:32,July 2023 - Sep 2023

In [23]:
import pandas as pd

# Assuming 'english_users_cleaned_copy' is already loaded in your environment

# Define the condition for the specific 'Username'
condition2 = english_users_cleaned_copy['Username'] == 'hong008sec@hotmail.com'

# Update the 'Country of birth' and 'Country you have_will immigrate from' columns
english_users_cleaned_copy.loc[condition2, ['Country of birth', 'Country you have_will immigrate from']] = 'China'

# Print only the specific record to verify the changes
english_users_cleaned_copy.loc[condition2]

,Username,FirstName,LastName,EmailAddress,Phone,City,Province,Country,Gender,Age,Status in Canada,Marital Status,Country of birth,Country you have_will immigrate from,Year landed in Canada enter 0 if not yet landed,Highest level of education,Cohort Name,Program Version,What is your current employment status,What industry or sector are you working in,Is this your preferred industry or sector,What is your current annual employment salary,Organization,DateAdded,Quarterly
392,hong008sec@hotmail.com,Liping,Wang,hong008sec@hotmail.com,2508120372,victoria,British Columbia,Canada,Female,50-59,Permanent Resident (In Canada),Single,China,China,2020.0,Less than high school,"VIRCS Jul - Sep, 2023",Online,5) Unemployed,01) I am not currently employed,1) Yes,1) I am not currently employed,NaN,2023-07-25 10:57,July 2023 - Sep 2023

In [24]:

# Assuming 'english_users_cleaned_copy' is already loaded in your environment

# Define the condition for the specific 'Username'
condition3 = english_users_cleaned_copy['Username'] == 'chudasama.h@northeastern.edu'

# Update the 'Country of birth' and 'Country you have_will immigrate from' columns
english_users_cleaned_copy.loc[condition3, ['Country you have_will immigrate from']] = 'Canada'

# Print only the specific record to verify the changes
english_users_cleaned_copy.loc[condition3]

,Username,FirstName,LastName,EmailAddress,Phone,City,Province,Country,Gender,Age,Status in Canada,Marital Status,Country of birth,Country you have_will immigrate from,Year landed in Canada enter 0 if not yet landed,Highest level of education,Cohort Name,Program Version,What is your current employment status,What industry or sector are you working in,Is this your preferred industry or sector,What is your current annual employment salary,Organization,DateAdded,Quarterly
36,chudasama.h@northeastern.edu,Harshil,Chudasama,chudasama.h@northeastern.edu,6478985470,Vancouver,British Columbia,Canada,Male,20-29,Canadian citizen,Single,Canada,Canada,1996.0,Graduate degree,"NU (Feb - May, 2024)",Online,2) In school or training,01) I am not currently employed,2) No,1) I am not currently employed,NaN,2024-02-13 0:51,Jan 2024 - Mar 2024

In [91]:
# Assuming 'english_users_cleaned_copy' is already loaded in your environment

# Define the condition for the specific 'Username'
condition4 = english_users_cleaned_copy['Username'] == 'howladerony@gmail.com'

# Update the 'Country of birth' and 'Country you have_will immigrate from' columns
english_users_cleaned_copy.loc[condition4, [ 'Country you have_will immigrate from']] = 'Bangladesh'

# Print only the specific record to verify the changes
english_users_cleaned_copy.loc[condition4]

,Username,FirstName,LastName,EmailAddress,Phone,City,Province,Country,Gender,Age,Status in Canada,Marital Status,Country of birth,Country you have_will immigrate from,Year landed in Canada enter 0 if not yet landed,Highest level of education,Cohort Name,Program Version,What is your current employment status,What industry or sector are you working in,Is this your preferred industry or sector,What is your current annual employment salary,Organization,DateAdded,Quarterly
810,howladerony@gmail.com,Rony,Howlader,howladerony@gmail.com,4375568667,Nanaimo,British Columbia,Canada,Male,20-29,Student with work visa,Married/live with partner,Bangladesh,Bangladesh,2022.0,Graduate degree,"CVIMS2 Oct - Jan, 2024",Blended,2) In school or training,04) Utilities,1) Yes,"2) Less than $25,000",NaN,2023-10-26 0:35,Oct 2023 - Dec 2023

In [25]:
# Assuming 'english_users_cleaned_copy' is already loaded in your environment

# Define the condition for the specific 'Username'
condition5 = english_users_cleaned_copy['Username'] == 'liujun02122023@163.com'

# Update the 'Country of birth' and 'Country you have_will immigrate from' columns
english_users_cleaned_copy.loc[condition5, ['Country you have_will immigrate from']] = 'China'

# Print only the specific record to verify the changes
english_users_cleaned_copy.loc[condition5]

,Username,FirstName,LastName,EmailAddress,Phone,City,Province,Country,Gender,Age,Status in Canada,Marital Status,Country of birth,Country you have_will immigrate from,Year landed in Canada enter 0 if not yet landed,Highest level of education,Cohort Name,Program Version,What is your current employment status,What industry or sector are you working in,Is this your preferred industry or sector,What is your current annual employment salary,Organization,DateAdded,Quarterly
478,liujun02122023@163.com,Jun,Liu,liujun02122023@163.com,13397112191,Wuhan,Hubei,China,Female,30-39,Student with work visa,Single,China,China,0.0,Graduate degree,"NU Jul - Oct, 2023",Blended,6) Other,01) I am not currently employed,2) No,1) I am not currently employed,NaN,2023-08-02 6:29,July 2023 - Sep 2023

In [30]:


# Assuming 'english_users_cleaned_copy' is already loaded in your environment

# Define the condition for the specific 'Username'
condition6 = english_users_cleaned_copy['Username'] == 'danitacarrasco@hotmail.com'

# Update the 'Country of birth' and 'Country you have_will immigrate from' columns
english_users_cleaned_copy.loc[condition6, ['Country of birth', 'Country you have_will immigrate from']] = 'Chile'

# Print only the specific record to verify the changes
english_users_cleaned_copy.loc[condition6]

,Username,FirstName,LastName,EmailAddress,Phone,City,Province,Country,Gender,Age,Status in Canada,Marital Status,Country of birth,Country you have_will immigrate from,Year landed in Canada enter 0 if not yet landed,Highest level of education,Cohort Name,Program Version,What is your current employment status,What industry or sector are you working in,Is this your preferred industry or sector,What is your current annual employment salary,Organization,DateAdded,Quarterly
319,danitacarrasco@hotmail.com,Daniela,Carrasco,danitacarrasco@hotmail.com,4372387826,Etobicoke,Ontario,Canada,Female,40-49,Temporary Foreign Worker (IRPR s.112 work permit),Married/live with partner,Chile,Chile,2023.0,Diploma,"WWCC Sep - Oct, 2023",Online,5) Unemployed,01) I am not currently employed,2) No,1) I am not currently employed,NaN,2023-09-11 20:19,July 2023 - Sep 2023

In [31]:


# Assuming 'english_users_cleaned_copy' is already loaded in your environment

# Define the condition for the specific 'Username'
condition7 = english_users_cleaned_copy['Username'] == 'feng.xiaom@northeastern.edu'

# Update the 'Country of birth' and 'Country you have_will immigrate from' columns
english_users_cleaned_copy.loc[condition7, ['Country of birth', 'Country you have_will immigrate from']] = 'China'

# Print only the specific record to verify the changes
english_users_cleaned_copy.loc[condition7]

,Username,FirstName,LastName,EmailAddress,Phone,City,Province,Country,Gender,Age,Status in Canada,Marital Status,Country of birth,Country you have_will immigrate from,Year landed in Canada enter 0 if not yet landed,Highest level of education,Cohort Name,Program Version,What is your current employment status,What industry or sector are you working in,Is this your preferred industry or sector,What is your current annual employment salary,Organization,DateAdded,Quarterly
357,feng.xiaom@northeastern.edu,Xiaomeng,Feng,feng.xiaom@northeastern.edu,13120128058,Beijing,Beijing,China,Male,30-39,Student with work visa,Married/live with partner,China,China,0.0,Graduate degree,"NU Jul - Oct, 2023",Blended,1) Employed,"13) Professional, scientific and technical ser...",1) Yes,"4) $50,000 - $75,000",NaN,2023-07-31 16:21,July 2023 - Sep 2023

In [32]:


# Assuming 'english_users_cleaned_copy' is already loaded in your environment

# Define the condition for the specific 'Username'
condition8 = english_users_cleaned_copy['Username'] == 'Rajindersingh090990@gmail.com'

# Update the 'Country of birth' and 'Country you have_will immigrate from' columns
english_users_cleaned_copy.loc[condition8, ['Country of birth', 'Country you have_will immigrate from']] = 'India'

# Print only the specific record to verify the changes
english_users_cleaned_copy.loc[condition8]

,Username,FirstName,LastName,EmailAddress,Phone,City,Province,Country,Gender,Age,Status in Canada,Marital Status,Country of birth,Country you have_will immigrate from,Year landed in Canada enter 0 if not yet landed,Highest level of education,Cohort Name,Program Version,What is your current employment status,What industry or sector are you working in,Is this your preferred industry or sector,What is your current annual employment salary,Organization,DateAdded,Quarterly
869,Rajindersingh090990@gmail.com,Rajinder,Singh,Rajindersingh090990@gmail.com,6043002807,Delta,British Columbia,Canada,Male,30-39,Permanent Resident (In Canada),Married/live with partner,India,India,2023.0,Graduate degree,"PICS Oct- Dec, 2023",Blended,1) Employed,09) Transportation and warehousing,2) No,"2) Less than $25,000",NaN,2023-10-12 8:36,Oct 2023 - Dec 2023

In [63]:

# Assuming 'english_users_cleaned_copy' is already loaded in your environment

# Define the condition for the specific 'Username'
condition10 = english_users_cleaned_copy['Username'] == 'howladerony@gmail.com'

# Update the 'Country of birth' and 'Country you have_will immigrate from' columns
english_users_cleaned_copy.loc[condition10, ['Country of birth', 'Country you have_will immigrate from']] = 'Bangladesh'

# Print only the specific record to verify the changes
english_users_cleaned_copy.loc[condition10]

,Username,FirstName,LastName,EmailAddress,Phone,City,Province,Country,Gender,Age,Status in Canada,Marital Status,Country of birth,Country you have_will immigrate from,Year landed in Canada enter 0 if not yet landed,Highest level of education,Cohort Name,Program Version,What is your current employment status,What industry or sector are you working in,Is this your preferred industry or sector,What is your current annual employment salary,Organization,DateAdded,Quarterly
810,howladerony@gmail.com,Rony,Howlader,howladerony@gmail.com,4375568667,Nanaimo,British Columbia,Canada,Male,20-29,Student with work visa,Married/live with partner,Bangladesh,Bangladesh,2022.0,Graduate degree,"CVIMS2 Oct - Jan, 2024",Blended,2) In school or training,04) Utilities,1) Yes,"2) Less than $25,000",NaN,2023-10-26 0:35,Oct 2023 - Dec 2023

In [26]:
import pandas as pd

# Assuming 'english_users_cleaned_copy' is already loaded in your environment

# Define the list of usernames you want to filter
usernames_to_display = [
    'fessehad27@gmail.com',
    'hong008sec@hotmail.com',
    'chudasama.h@northeastern.edu',
    'howladerony@gmail.com',
    'liujun02122023@163.com'
]

# Filter the DataFrame to show only the specified usernames
filtered_df = english_users_cleaned_copy[english_users_cleaned_copy['Username'].isin(usernames_to_display)]

# Display the filtered DataFrame
filtered_df

,Username,FirstName,LastName,EmailAddress,Phone,City,Province,Country,Gender,Age,Status in Canada,Marital Status,Country of birth,Country you have_will immigrate from,Year landed in Canada enter 0 if not yet landed,Highest level of education,Cohort Name,Program Version,What is your current employment status,What industry or sector are you working in,Is this your preferred industry or sector,What is your current annual employment salary,Organization,DateAdded,Quarterly
36,chudasama.h@northeastern.edu,Harshil,Chudasama,chudasama.h@northeastern.edu,6478985470,Vancouver,British Columbia,Canada,Male,20-29,Canadian citizen,Single,Canada,Canada,1996.0,Graduate degree,"NU (Feb - May, 2024)",Online,2) In school or training,01) I am not currently employed,2) No,1) I am not currently employed,NaN,2024-02-13 0:51,Jan 2024 - Mar 2024
360,fessehad27@gmail.com,FESSEHA,TEWOLDEMDHIN,fessehad27@gmail.com,7785876427,Victoria,British Columbia,Canada,Male,40-49,Permanent Resident (In Canada),Married/live with partner,Euthiopia,Euthiopia,0.0,Diploma,"VIRCS Jul - Sep, 2023",Online,1) Employed,05) Construction,1) Yes,"2) Less than $25,000",NaN,2023-07-25 19:32,July 2023 - Sep 2023
392,hong008sec@hotmail.com,Liping,Wang,hong008sec@hotmail.com,2508120372,victoria,British Columbia,Canada,Female,50-59,Permanent Resident (In Canada),Single,China,China,2020.0,Less than high school,"VIRCS Jul - Sep, 2023",Online,5) Unemployed,01) I am not currently employed,1) Yes,1) I am not currently employed,NaN,2023-07-25 10:57,July 2023 - Sep 2023
478,liujun02122023@163.com,Jun,Liu,liujun02122023@163.com,13397112191,Wuhan,Hubei,China,Female,30-39,Student with work visa,Single,China,China,0.0,Graduate degree,"NU Jul - Oct, 2023",Blended,6) Other,01) I am not currently employed,2) No,1) I am not currently employed,NaN,2023-08-02 6:29,July 2023 - Sep 2023
810,howladerony@gmail.com,Rony,Howlader,howladerony@gmail.com,4375568667,Nanaimo,British Columbia,Canada,Male,20-29,Student with work visa,Married/live with partner,Bangladesh,Im already in Canada,2022.0,Graduate degree,"CVIMS2 Oct - Jan, 2024",Blended,2) In school or training,04) Utilities,1) Yes,"2) Less than $25,000",NaN,2023-10-26 0:35,Oct 2023 - Dec 2023

In [27]:
english_users_cleaned_copy.isnull().sum()

Username                                             0
FirstName                                            0
LastName                                             0
EmailAddress                                         0
Phone                                                0
City                                                 0
Province                                             0
Country                                              0
Gender                                               0
Age                                                  0
Status in Canada                                     0
Marital Status                                       0
Country of birth                                     0
Country you have_will immigrate from                 4
Year landed in Canada enter 0 if not yet landed      0
Highest level of education                           0
Cohort Name                                          0
Program Version                                      0
What is your current employment status               1
What industry or sector are you working in           1
Is this your preferred industry or sector            1
What is your current annual employment salary        1
Organization                                       803
DateAdded                                            0
Quarterly                                            0
dtype: int64

In [34]:
import os
# Define the path where you want to save the CSV file
save_path = os.path.join(os.getcwd(), 'english_users_cleaned_copy1.csv')

# Save the english_users DataFrame to a CSV file
english_users_cleaned_copy.to_csv(save_path, index=False)

# Function to return the save path
def get_save_path():
    return save_path

# Print the path where the dataset has been saved
print(f"English users dataset has been saved at: {get_save_path()}")

English users dataset has been saved at: /content/english_users_cleaned_copy1.csv

In [29]:

# Define the list of usernames for which you want to update the 'Country you have_will immigrate from'
usernames_to_update = [
    'feng.chenc@northeastern.edu',
    'pink_gricel95@hotmail.com',
    'wu.hao11@northeastern.edu',
    'zeng.zhix@northeastern.edu',
    'obaidamourad357@gmail.com'
]

# Update the 'Country you have_will immigrate from' to match 'Country of birth' for the specified usernames
english_users_cleaned_copy.loc[
    english_users_cleaned_copy['Username'].isin(usernames_to_update),
    'Country you have_will immigrate from'
] = english_users_cleaned_copy.loc[
    english_users_cleaned_copy['Username'].isin(usernames_to_update),
    'Country of birth'
]

# Display the updated records to verify the changes
updated_records = english_users_cleaned_copy[english_users_cleaned_copy['Username'].isin(usernames_to_update)]
updated_records

,Username,FirstName,LastName,EmailAddress,Phone,City,Province,Country,Gender,Age,Status in Canada,Marital Status,Country of birth,Country you have_will immigrate from,Year landed in Canada enter 0 if not yet landed,Highest level of education,Cohort Name,Program Version,What is your current employment status,What industry or sector are you working in,Is this your preferred industry or sector,What is your current annual employment salary,Organization,DateAdded,Quarterly
61,feng.chenc@northeastern.edu,Chenchen,Feng,feng.chenc@northeastern.edu,7785580478,Vancouver,British Columbia,Canada,Female,Prefer not to disclose,Student with work visa,Prefer not to disclose,China,China,2024.0,Graduate degree,"NU (Feb - May, 2024)",Online,2) In school or training,01) I am not currently employed,2) No,1) I am not currently employed,NaN,2024-02-07 6:24,Jan 2024 - Mar 2024
566,pink_gricel95@hotmail.com,Gricel,Avendano Aguilar,pink_gricel95@hotmail.com,4372405457,"Toronto, ON",Ontario,Canada,Prefer not to disclose,20-29,Convention Refugee,Single,Mexico,Mexico,2022.0,Degree,"WWCC Jul - Sep, 2023",Online,2) In school or training,01) I am not currently employed,1) Yes,1) I am not currently employed,NaN,2023-07-25 10:10,July 2023 - Sep 2023
670,wu.hao11@northeastern.edu,Hao,Wu,wu.hao11@northeastern.edu,8.61575E+12,Guangzhou,Guangdong,China,Male,20-29,Student with work visa,Prefer not to disclose,China,China,0.0,Graduate degree,"NU Jul - Oct, 2023",Blended,"3) On leave from employment (Leave of absence,...",11) Finance and insurance,2) No,"5) $75,000 - $100,000",NaN,2023-08-02 0:16,July 2023 - Sep 2023
711,zeng.zhix@northeastern.edu,Zhixin,Zeng,zeng.zhix@northeastern.edu,8.6183E+12,Chongqing,Chongqing,China,Male,20-29,Student with work visa,Single,China,China,0.0,Degree,"NU Jul - Oct, 2023",Blended,5) Unemployed,01) I am not currently employed,2) No,1) I am not currently employed,NaN,2023-07-20 21:30,July 2023 - Sep 2023
854,obaidamourad357@gmail.com,Obaida,Mourad,obaidamourad357@gmail.com,506-898-6889,Saint John,New Brunswick,Canada,Male,20-29,Permanent Resident (In Canada),Single,UAE,UAE,2022.0,High school diploma or equivalent,"SJNC Dec - Jan, 2024",Online,5) Unemployed,01) I am not currently employed,2) No,1) I am not currently employed,NaN,2023-12-11 11:12,Oct 2023 - Dec 2023

# Data Cleaning for Mis-Spelling of the Country
- Brasil to Brazil
- 'china','CN','China, PeopleÂ’s Republic of','Chinia','Hong Kong','Hong Kong, China'
-Euthiopia to Ethiopia
- Hyderabad to 'India
-korea variations
-MÃ©xico to Mexico
-PerÃº to Peru
-Ukraine_variations
- Canada_variations
- Nigeria_variations
- North to Iran
-rawanda to
-Turkey_variations
- UEA_VARIATIONS to United Arab Emirates
- US TO USA

In [36]:
# Update 'Country you have_will immigrate from' column from 'Brasil' to 'Brazil'
english_users_cleaned_copy['Country you have_will immigrate from'] = english_users_cleaned_copy['Country you have_will immigrate from'].replace('Brasil', 'Brazil')

# Update 'Country of birth' column from 'Brasil' to 'Brazil'
english_users_cleaned_copy['Country of birth'] = english_users_cleaned_copy['Country of birth'].replace('Brasil', 'Brazil')

In [100]:
# List of variations to be replaced with 'China'
variations_to_replace = ['china', 'CN', 'China, PeopleÂ’s Republic of', 'Chinia', 'Hong Kong', 'Hong Kong, China',"China, PeopleÂ’s Republic of ","China, PeopleÂ’s Republic of"]

# Update 'Country you have_will immigrate from' column
english_users_cleaned_copy['Country you have_will immigrate from'] = english_users_cleaned_copy['Country you have_will immigrate from'].replace(variations_to_replace, 'China')

# Update 'Country of birth' column
english_users_cleaned_copy['Country of birth'] = english_users_cleaned_copy['Country of birth'].replace(variations_to_replace, 'China')

In [108]:
# Load the DataFrame with correct encoding (if necessary)
# english_users_cleaned_copy = pd.read_csv('your_file.csv', encoding='utf-8')

# Correct the replacement of 'PerÃº' to 'Peru' considering special characters
english_users_cleaned_copy['Country you have_will immigrate from'] = english_users_cleaned_copy['Country you have_will immigrate from'].str.replace('China, PeopleÂ’s Republic of ', 'China', regex=False)
english_users_cleaned_copy['Country of birth'] = english_users_cleaned_copy['Country of birth'].str.replace('China, PeopleÂ’s Republic of ', 'China', regex=False)

# Optionally, normalize the text to handle any special characters
english_users_cleaned_copy['Country you have_will immigrate from'] = english_users_cleaned_copy['Country you have_will immigrate from'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
english_users_cleaned_copy['Country of birth'] = english_users_cleaned_copy['Country of birth'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')

In [41]:
# Update 'Country you have_will immigrate from' column from 'Brasil' to 'Brazil'
english_users_cleaned_copy['Country you have_will immigrate from'] = english_users_cleaned_copy['Country you have_will immigrate from'].replace('Euthiopia', 'Ethiopia')

# Update 'Country of birth' column from 'Brasil' to 'Brazil'
english_users_cleaned_copy['Country of birth'] = english_users_cleaned_copy['Country of birth'].replace('Euthiopia', 'Ethiopia')

In [50]:
# Update 'Country of birth' column from 'Brasil' to 'Brazil'
english_users_cleaned_copy['Country of birth'] = english_users_cleaned_copy['Country of birth'].replace('Hyderabad ', 'India')

In [52]:

# List of variations to be replaced with 'South Korea'
korea_variations = ['Korea','South Korea','Korea, Republic of', 'Republic of Korea', 'Korea South']

# Update 'Country you have_will immigrate from' column
english_users_cleaned_copy['Country you have_will immigrate from'] = english_users_cleaned_copy['Country you have_will immigrate from'].replace(korea_variations, 'South Korea')

# Update 'Country of birth' column
english_users_cleaned_copy['Country of birth'] = english_users_cleaned_copy['Country of birth'].replace(korea_variations, 'South Korea')

In [54]:
# Update 'Country you have_will immigrate from' column from 'Brasil' to 'Brazil'
english_users_cleaned_copy['Country you have_will immigrate from'] = english_users_cleaned_copy['Country you have_will immigrate from'].replace('MÃ©xico', 'Mexico')

# Update 'Country of birth' column from 'Brasil' to 'Brazil'
english_users_cleaned_copy['Country of birth'] = english_users_cleaned_copy['Country of birth'].replace('MÃ©xico', 'Mexico')

In [104]:
# Load the DataFrame with correct encoding (if necessary)
# english_users_cleaned_copy = pd.read_csv('your_file.csv', encoding='utf-8')

# Correct the replacement of 'PerÃº' to 'Peru' considering special characters
english_users_cleaned_copy['Country you have_will immigrate from'] = english_users_cleaned_copy['Country you have_will immigrate from'].str.replace('MÃ©xico', 'Mexico', regex=False)
english_users_cleaned_copy['Country of birth'] = english_users_cleaned_copy['Country of birth'].str.replace('MÃ©xico', 'Mexico', regex=False)

# Optionally, normalize the text to handle any special characters
english_users_cleaned_copy['Country you have_will immigrate from'] = english_users_cleaned_copy['Country you have_will immigrate from'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
english_users_cleaned_copy['Country of birth'] = english_users_cleaned_copy['Country of birth'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')

In [56]:
# Update 'Country you have_will immigrate from' column from 'Brasil' to 'Brazil'
english_users_cleaned_copy['Country you have_will immigrate from'] = english_users_cleaned_copy['Country you have_will immigrate from'].replace('PerÃº', 'Peru')

# Update 'Country of birth' column from 'Brasil' to 'Brazil'
english_users_cleaned_copy['Country of birth'] = english_users_cleaned_copy['Country of birth'].replace('PerÃº', 'Peru')

In [102]:
# Load the DataFrame with correct encoding (if necessary)
# english_users_cleaned_copy = pd.read_csv('your_file.csv', encoding='utf-8')

# Correct the replacement of 'PerÃº' to 'Peru' considering special characters
english_users_cleaned_copy['Country you have_will immigrate from'] = english_users_cleaned_copy['Country you have_will immigrate from'].str.replace('PerÃº', 'Peru', regex=False)
english_users_cleaned_copy['Country of birth'] = english_users_cleaned_copy['Country of birth'].str.replace('PerÃº', 'Peru', regex=False)

# Optionally, normalize the text to handle any special characters
english_users_cleaned_copy['Country you have_will immigrate from'] = english_users_cleaned_copy['Country you have_will immigrate from'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
english_users_cleaned_copy['Country of birth'] = english_users_cleaned_copy['Country of birth'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')

In [120]:
# List of variations to be replaced with 'South Korea'
Ukraine_variations = ['Ukraine ','Ukrainian','Kyiv', 'Ukrain','Ikey','Ukrainian','Ukrainian ','Ukraine/Canada']

# Update 'Country you have_will immigrate from' column
english_users_cleaned_copy['Country you have_will immigrate from'] = english_users_cleaned_copy['Country you have_will immigrate from'].replace(Ukraine_variations, 'Ukraine')

# Update 'Country of birth' column
english_users_cleaned_copy['Country of birth'] = english_users_cleaned_copy['Country of birth'].replace(Ukraine_variations, 'Ukraine')

In [112]:
# Update 'Country you have_will immigrate from' column from 'Brasil' to 'Brazil'
english_users_cleaned_copy['Country you have_will immigrate from'] = english_users_cleaned_copy['Country you have_will immigrate from'].replace('Viet Nam', 'Vietnam')

# Update 'Country of birth' column from 'Brasil' to 'Brazil'
english_users_cleaned_copy['Country of birth'] = english_users_cleaned_copy['Country of birth'].replace('Viet Nam', 'Vietnam')

In [116]:
# List of variations to be replaced with 'South Korea'
Canada_variations = ['British Columbia','British Colombia canada','British Colombia canada ','CanadÃ¡']

# Update 'Country you have_will immigrate from' column
english_users_cleaned_copy['Country you have_will immigrate from'] = english_users_cleaned_copy['Country you have_will immigrate from'].replace(Canada_variations, 'Canada')

# Update 'Country of birth' column
english_users_cleaned_copy['Country of birth'] = english_users_cleaned_copy['Country of birth'].replace(Canada_variations, 'Canada')

In [118]:
# Correct the replacement of 'PerÃº' to 'Peru' considering special characters
english_users_cleaned_copy['Country you have_will immigrate from'] = english_users_cleaned_copy['Country you have_will immigrate from'].str.replace('CanadÃ¡', 'Canada', regex=False)
english_users_cleaned_copy['Country of birth'] = english_users_cleaned_copy['Country of birth'].str.replace('CanadÃ¡', 'Canada', regex=False)

# Optionally, normalize the text to handle any special characters
english_users_cleaned_copy['Country you have_will immigrate from'] = english_users_cleaned_copy['Country you have_will immigrate from'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
english_users_cleaned_copy['Country of birth'] = english_users_cleaned_copy['Country of birth'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')

In [78]:
# List of variations to be replaced with 'South Korea'
Pakistan_variations = ['PAKISTAN ','Pakistani','pakistan ','Pakistani ']

# Update 'Country you have_will immigrate from' column
english_users_cleaned_copy['Country you have_will immigrate from'] = english_users_cleaned_copy['Country you have_will immigrate from'].replace(Pakistan_variations, 'Pakistan')

# Update 'Country of birth' column
english_users_cleaned_copy['Country of birth'] = english_users_cleaned_copy['Country of birth'].replace(Pakistan_variations, 'Pakistan')

In [69]:
# List of variations to be replaced with 'South Korea'
Nigeria_variations = ['NIGERIA','lagos','Nigerian']

# Update 'Country you have_will immigrate from' column
english_users_cleaned_copy['Country you have_will immigrate from'] = english_users_cleaned_copy['Country you have_will immigrate from'].replace(Nigeria_variations, 'Nigeria')

# Update 'Country of birth' column
english_users_cleaned_copy['Country of birth'] = english_users_cleaned_copy['Country of birth'].replace(Nigeria_variations, 'Nigeria')

In [67]:
# Update 'Country you have_will immigrate from' column from 'Brasil' to 'Brazil'
english_users_cleaned_copy['Country you have_will immigrate from'] = english_users_cleaned_copy['Country you have_will immigrate from'].replace('North', 'Iran')

In [81]:
# Update 'Country you have_will immigrate from' column from 'Brasil' to 'Brazil'
english_users_cleaned_copy['Country you have_will immigrate from'] = english_users_cleaned_copy['Country you have_will immigrate from'].replace('Rwanada', 'Rwanda')

In [83]:
# List of variations to be replaced with 'South Korea'
Turkey_variations = ['turky','turkiy']

# Update 'Country you have_will immigrate from' column
english_users_cleaned_copy['Country you have_will immigrate from'] = english_users_cleaned_copy['Country you have_will immigrate from'].replace(Turkey_variations, 'Turkey')

# Update 'Country of birth' column
english_users_cleaned_copy['Country of birth'] = english_users_cleaned_copy['Country of birth'].replace(Turkey_variations, 'Turkey')

In [86]:
# List of variations to be replaced with 'South Korea'
UAE_variations = ['UEA','UAE','United Arab Emirates','United Arab Emirates  ','United Arab Emarites','United Arab Emarites ']

# Update 'Country you have_will immigrate from' column
english_users_cleaned_copy['Country you have_will immigrate from'] = english_users_cleaned_copy['Country you have_will immigrate from'].replace(UAE_variations, 'United Arab Emirates')

# Update 'Country of birth' column
english_users_cleaned_copy['Country of birth'] = english_users_cleaned_copy['Country of birth'].replace(Nigeria_variations, 'United Arab Emirates')

In [87]:
# Update 'Country you have_will immigrate from' column from 'Brasil' to 'Brazil'
english_users_cleaned_copy['Country you have_will immigrate from'] = english_users_cleaned_copy['Country you have_will immigrate from'].replace('US', 'USA')

In [114]:
# List of variations to be replaced with 'South Korea'
afghanistan_variations = ['Afghanistan','Afganistan','Afghanistan']

# Update 'Country you have_will immigrate from' column
english_users_cleaned_copy['Country you have_will immigrate from'] = english_users_cleaned_copy['Country you have_will immigrate from'].replace(afghanistan_variations, 'Afghanistan')

# Update 'Country of birth' column
english_users_cleaned_copy['Country of birth'] = english_users_cleaned_copy['Country of birth'].replace(afghanistan_variations, 'Afghanistan')

In [121]:
# Define the condition for the specific 'Username'
condition9 = english_users_cleaned_copy['Username'] == 'viktoriyadidok@gmail.com'
english_users_cleaned_copy.loc[condition9]

,Username,FirstName,LastName,EmailAddress,Phone,City,Province,Country,Gender,Age,Status in Canada,Marital Status,Country of birth,Country you have_will immigrate from,Year landed in Canada enter 0 if not yet landed,Highest level of education,Cohort Name,Program Version,What is your current employment status,What industry or sector are you working in,Is this your preferred industry or sector,What is your current annual employment salary,Organization,DateAdded,Quarterly
903,viktoriyadidok@gmail.com,Viktoriya,Didok,viktoriyadidok@gmail.com,(647)224-6417,Lethbrige,Alberta,Canada,Female,40-49,Spouse of Permanent Resident Principal Applica...,Married/live with partner,Ukraine,Ukraine,2023.0,Diploma,"LFS Nov - Jan, 2024",Online,5) Unemployed,"18) Arts, entertainment and recreation",1) Yes,1) I am not currently employed,Prefer not to disclose,2023-11-27 12:56,Oct 2023 - Dec 2023

Change in 'What is your current annual employment salary'
- 3) $25,000 Â– $50,000 to 3) $25,000 – $50,000

In [88]:
# Update 'Country you have_will immigrate from' column from 'Brasil' to 'Brazil'
english_users_cleaned_copy['What is your current annual employment salary'] = english_users_cleaned_copy['What is your current annual employment salary'].replace('3) $25,000 Â– $50,000', '3) $25,000 – $50,000')

# Organization fill na with 'Prefer not to disclose'

## drop na values

In [92]:
# Update null values in 'Organization' column to 'Prefer not to disclose'
english_users_cleaned_copy['Organization'] = english_users_cleaned_copy['Organization'].fillna('Prefer not to disclose')

In [94]:
# Drop records with any null values
english_users_cleaned_copy = english_users_cleaned_copy.dropna()

In [95]:
english_users_cleaned_copy.isnull().sum()

Username                                           0
FirstName                                          0
LastName                                           0
EmailAddress                                       0
Phone                                              0
City                                               0
Province                                           0
Country                                            0
Gender                                             0
Age                                                0
Status in Canada                                   0
Marital Status                                     0
Country of birth                                   0
Country you have_will immigrate from               0
Year landed in Canada enter 0 if not yet landed    0
Highest level of education                         0
Cohort Name                                        0
Program Version                                    0
What is your current employment status             0
What industry or sector are you working in         0
Is this your preferred industry or sector          0
What is your current annual employment salary      0
Organization                                       0
DateAdded                                          0
Quarterly                                          0
dtype: int64

# Download the English user cleaned dataset

In [122]:
import os

# Define the path where you want to save the CSV file
save_path = os.path.join(os.getcwd(), 'english_users_cleaned.csv')

# Save the english_users DataFrame to a CSV file
english_users_cleaned_copy.to_csv(save_path, index=False)

# Function to return the save path
def get_save_path():
    return save_path

# Print the path where the dataset has been saved
print(f"English users dataset has been saved at: {get_save_path()}")

English users dataset has been saved at: /content/english_users_cleaned.csv